version: '3.1'

services:

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
      POSTGRES_DB: app
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
